;compare 2 values

.MODEL SMALL
.DATA
    NUM1 DB 93H
    NUM2 DB 23H
    MSG DB "BOTH ARE EQUAL $"
    MSG1 DB "NUM1 IS LESS THAN NUM2 $" 
    MSG2 DB "NUM1 IS GREATER THAN NUM2 $"

.CODE
   MOV AX,@DATA
   MOV DS,AX
   MOV AH,NUM1
   MOV CH,NUM2
   CMP AH,CH
   JE L1      ;IF AH AND CH ARE EQUAL 
   JB L2      ;IF AH IS LESS THAN CH 
   JA L3      ;IF AH IS GREATER THAN CH 

L1:
   MOV DX, OFFSET MSG
   MOV AH,09H        ;PRINT THE MSG STDOUT
   INT 21H
   RET

L2:
   MOV DX, OFFSET MSG1
   MOV AH,09H          ;PRINT THE MSG STDOUT
   INT 21H
   RET

L3:
   MOV DX, OFFSET MSG2
   MOV AH,09H
   INT 21H
   RET
END
